### PR TITLE
Completed css-canvas-medical first-Page. | Rakesh

### PR DESCRIPTION
**Pull request by bhaisingh**
image

### CODE REVIEW

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
initially it looks good. Please do the following:
1. adjust the colors on the page to more closely match the colors of the original (fonts, buttons, backgrounds. etc)
2. Submit a new image once you have updated it which shows the entire page.

**Comment by bhaisingh** [comment]
image

image

**Review by BrettAlbright — APPROVED** [review]
Coming together really nicely! Just a couple of adjustments to go:
1. In the clinicians prefer canvas section, the should be more space between the two text columns
2. In the ready to learn more section, the `Ready to learn more` text should be larger in relation to the text below it
3. In the dark gray footer section,  the Canvas text and address should not be italic, and the columns under `Company` and `Product` should be aligned and have more space between them. 

Keep up the good work Rakesh!

**Review by BrettAlbright — CHANGES_REQUESTED** [review]
sorry, hit the wrong button before!

**Comment by bhaisingh** [comment]
image

**Review by BrettAlbright — APPROVED** [review]
👍

**Pull request merged**
